-- ============================================================
-- 실제 59개 사업장 명칭 + 품목별 예정수량 반영
-- 원본: '사업장, 품목 리스트.xlsx' (세부 견적서, 59개 사업장 합계 기준)
-- 전제: 02_seed_placeholder.sql 로 생성된 sites.id 가 1~59 이고,
--       엑셀의 No 순서와 site id 가 1:1로 대응한다는 가정입니다.
-- 담당업체(contractor_id)는 아직 미확정이라 이 스크립트에서는 건드리지 않습니다.
--
-- 참고: A=비상벨(GST-502), B=리피터(GX-8200), C=모뎀(GX-8200 TCP/IP)
-- ============================================================

-- 1) 사업장명 갱신
update sites set name = '오토닉스' where id = 1;
update sites set name = '북부부품사업소' where id = 2;
update sites set name = '동부부품팀(H)' where id = 3;
update sites set name = '성동부품팀(K)' where id = 4;
update sites set name = '서부부품사업소' where id = 5;
update sites set name = '고양부품팀(H)' where id = 6;
update sites set name = '강원부품사업소' where id = 7;
update sites set name = '원주부품팀(K)' where id = 8;
update sites set name = '강릉부품사업소' where id = 9;
update sites set name = '춘천부품사업소' where id = 10;
update sites set name = '동부부품사업소' where id = 11;
update sites set name = '안성물류팀' where id = 12;
update sites set name = '남부부품사업소' where id = 13;
update sites set name = '인천부품사업소' where id = 14;
update sites set name = '인천부품팀(K)' where id = 15;
update sites set name = '시화부품팀(H)' where id = 16;
update sites set name = '시흥부품팀(K)' where id = 17;
update sites set name = '인천사외창고' where id = 18;
update sites set name = '충청부품사업소' where id = 19;
update sites set name = '대전물류팀' where id = 20;
update sites set name = '대전부품팀(K)' where id = 21;
update sites set name = '청주부품팀(H)' where id = 22;
update sites set name = '서산부품사업소' where id = 23;
update sites set name = '전북부품사업소' where id = 24;
update sites set name = '전북부품사업소(K)' where id = 25;
update sites set name = '전주부품팀(H)' where id = 26;
update sites set name = '전남부품사업소' where id = 27;
update sites set name = '목포부품사업소' where id = 28;
update sites set name = '순천부품사업소' where id = 29;
update sites set name = '순천부품팀(H)' where id = 30;
update sites set name = '제주부품사업소' where id = 31;
update sites set name = '제주부품팀(H)' where id = 32;
update sites set name = '제주부품팀(K)' where id = 33;
update sites set name = '아산물류센터' where id = 34;
update sites set name = '입장' where id = 35;
update sites set name = '천안물류' where id = 36;
update sites set name = '천안친환경' where id = 37;
update sites set name = '경북부품사업소' where id = 38;
update sites set name = '서대구부품팀' where id = 39;
update sites set name = '안동부품사업소' where id = 40;
update sites set name = '김천부품사업소' where id = 41;
update sites set name = '포항부품사업소' where id = 42;
update sites set name = '포항부품팀(H)' where id = 43;
update sites set name = '부산부품사업소' where id = 44;
update sites set name = '울산부품팀(H)' where id = 45;
update sites set name = '경남부품사업소(H)' where id = 46;
update sites set name = '경남부품사업소(K)' where id = 47;
update sites set name = '서부산부품팀(H)' where id = 48;
update sites set name = '진주부품사업소' where id = 49;
update sites set name = '영남물류센터' where id = 50;
update sites set name = '울산수출물류' where id = 51;
update sites set name = '사외창고(신항)' where id = 52;
update sites set name = '사외창고(서영)' where id = 53;
update sites set name = '본사' where id = 54;
update sites set name = '강남연구소' where id = 55;
update sites set name = '의왕연구소' where id = 56;
update sites set name = '울산전동화' where id = 57;
update sites set name = '대구전동화' where id = 58;
update sites set name = '아주빌딩 (본사)' where id = 59;

-- 2) 품목별 예정수량 갱신 (A=비상벨, B=리피터, C=모뎀)
update installations set planned_qty = 58 where site_id = 1 and product = 'A';
update installations set planned_qty = 7 where site_id = 1 and product = 'B';
update installations set planned_qty = 5 where site_id = 1 and product = 'C';
update installations set planned_qty = 9 where site_id = 2 and product = 'A';
update installations set planned_qty = 3 where site_id = 2 and product = 'B';
update installations set planned_qty = 3 where site_id = 2 and product = 'C';
update installations set planned_qty = 3 where site_id = 3 and product = 'A';
update installations set planned_qty = 2 where site_id = 3 and product = 'B';
update installations set planned_qty = 1 where site_id = 3 and product = 'C';
update installations set planned_qty = 2 where site_id = 4 and product = 'A';
update installations set planned_qty = 2 where site_id = 4 and product = 'B';
update installations set planned_qty = 1 where site_id = 4 and product = 'C';
update installations set planned_qty = 21 where site_id = 5 and product = 'A';
update installations set planned_qty = 6 where site_id = 5 and product = 'B';
update installations set planned_qty = 3 where site_id = 5 and product = 'C';
update installations set planned_qty = 3 where site_id = 6 and product = 'A';
update installations set planned_qty = 2 where site_id = 6 and product = 'B';
update installations set planned_qty = 1 where site_id = 6 and product = 'C';
update installations set planned_qty = 11 where site_id = 7 and product = 'A';
update installations set planned_qty = 2 where site_id = 7 and product = 'B';
update installations set planned_qty = 2 where site_id = 7 and product = 'C';
update installations set planned_qty = 2 where site_id = 8 and product = 'A';
update installations set planned_qty = 2 where site_id = 8 and product = 'B';
update installations set planned_qty = 1 where site_id = 8 and product = 'C';
update installations set planned_qty = 11 where site_id = 9 and product = 'A';
update installations set planned_qty = 2 where site_id = 9 and product = 'B';
update installations set planned_qty = 2 where site_id = 9 and product = 'C';
update installations set planned_qty = 6 where site_id = 10 and product = 'A';
update installations set planned_qty = 2 where site_id = 10 and product = 'B';
update installations set planned_qty = 1 where site_id = 10 and product = 'C';
update installations set planned_qty = 31 where site_id = 11 and product = 'A';
update installations set planned_qty = 6 where site_id = 11 and product = 'B';
update installations set planned_qty = 3 where site_id = 11 and product = 'C';
update installations set planned_qty = 32 where site_id = 12 and product = 'A';
update installations set planned_qty = 6 where site_id = 12 and product = 'B';
update installations set planned_qty = 3 where site_id = 12 and product = 'C';
update installations set planned_qty = 16 where site_id = 13 and product = 'A';
update installations set planned_qty = 4 where site_id = 13 and product = 'B';
update installations set planned_qty = 1 where site_id = 13 and product = 'C';
update installations set planned_qty = 15 where site_id = 14 and product = 'A';
update installations set planned_qty = 6 where site_id = 14 and product = 'B';
update installations set planned_qty = 2 where site_id = 14 and product = 'C';
update installations set planned_qty = 4 where site_id = 15 and product = 'A';
update installations set planned_qty = 2 where site_id = 15 and product = 'B';
update installations set planned_qty = 2 where site_id = 15 and product = 'C';
update installations set planned_qty = 3 where site_id = 16 and product = 'A';
update installations set planned_qty = 2 where site_id = 16 and product = 'B';
update installations set planned_qty = 1 where site_id = 16 and product = 'C';
update installations set planned_qty = 3 where site_id = 17 and product = 'A';
update installations set planned_qty = 2 where site_id = 17 and product = 'B';
update installations set planned_qty = 1 where site_id = 17 and product = 'C';
update installations set planned_qty = 11 where site_id = 18 and product = 'A';
update installations set planned_qty = 4 where site_id = 18 and product = 'B';
update installations set planned_qty = 2 where site_id = 18 and product = 'C';
update installations set planned_qty = 19 where site_id = 19 and product = 'A';
update installations set planned_qty = 5 where site_id = 19 and product = 'B';
update installations set planned_qty = 2 where site_id = 19 and product = 'C';
update installations set planned_qty = 7 where site_id = 20 and product = 'A';
update installations set planned_qty = 2 where site_id = 20 and product = 'B';
update installations set planned_qty = 1 where site_id = 20 and product = 'C';
update installations set planned_qty = 1 where site_id = 21 and product = 'A';
update installations set planned_qty = 2 where site_id = 21 and product = 'B';
update installations set planned_qty = 1 where site_id = 21 and product = 'C';
update installations set planned_qty = 4 where site_id = 22 and product = 'A';
update installations set planned_qty = 2 where site_id = 22 and product = 'B';
update installations set planned_qty = 1 where site_id = 22 and product = 'C';
update installations set planned_qty = 11 where site_id = 23 and product = 'A';
update installations set planned_qty = 2 where site_id = 23 and product = 'B';
update installations set planned_qty = 1 where site_id = 23 and product = 'C';
update installations set planned_qty = 12 where site_id = 24 and product = 'A';
update installations set planned_qty = 4 where site_id = 24 and product = 'B';
update installations set planned_qty = 2 where site_id = 24 and product = 'C';
update installations set planned_qty = 6 where site_id = 25 and product = 'A';
update installations set planned_qty = 4 where site_id = 25 and product = 'B';
update installations set planned_qty = 1 where site_id = 25 and product = 'C';
update installations set planned_qty = 1 where site_id = 26 and product = 'A';
update installations set planned_qty = 2 where site_id = 26 and product = 'B';
update installations set planned_qty = 1 where site_id = 26 and product = 'C';
update installations set planned_qty = 19 where site_id = 27 and product = 'A';
update installations set planned_qty = 4 where site_id = 27 and product = 'B';
update installations set planned_qty = 2 where site_id = 27 and product = 'C';
update installations set planned_qty = 8 where site_id = 28 and product = 'A';
update installations set planned_qty = 4 where site_id = 28 and product = 'B';
update installations set planned_qty = 2 where site_id = 28 and product = 'C';
update installations set planned_qty = 9 where site_id = 29 and product = 'A';
update installations set planned_qty = 4 where site_id = 29 and product = 'B';
update installations set planned_qty = 2 where site_id = 29 and product = 'C';
update installations set planned_qty = 3 where site_id = 30 and product = 'A';
update installations set planned_qty = 4 where site_id = 30 and product = 'B';
update installations set planned_qty = 1 where site_id = 30 and product = 'C';
update installations set planned_qty = 8 where site_id = 31 and product = 'A';
update installations set planned_qty = 4 where site_id = 31 and product = 'B';
update installations set planned_qty = 2 where site_id = 31 and product = 'C';
update installations set planned_qty = 4 where site_id = 32 and product = 'A';
update installations set planned_qty = 2 where site_id = 32 and product = 'B';
update installations set planned_qty = 1 where site_id = 32 and product = 'C';
update installations set planned_qty = 2 where site_id = 33 and product = 'A';
update installations set planned_qty = 2 where site_id = 33 and product = 'B';
update installations set planned_qty = 1 where site_id = 33 and product = 'C';
update installations set planned_qty = 76 where site_id = 34 and product = 'A';
update installations set planned_qty = 18 where site_id = 34 and product = 'B';
update installations set planned_qty = 6 where site_id = 34 and product = 'C';
update installations set planned_qty = 58 where site_id = 35 and product = 'A';
update installations set planned_qty = 18 where site_id = 35 and product = 'B';
update installations set planned_qty = 6 where site_id = 35 and product = 'C';
update installations set planned_qty = 14 where site_id = 36 and product = 'A';
update installations set planned_qty = 4 where site_id = 36 and product = 'B';
update installations set planned_qty = 2 where site_id = 36 and product = 'C';
update installations set planned_qty = 4 where site_id = 37 and product = 'A';
update installations set planned_qty = 4 where site_id = 37 and product = 'B';
update installations set planned_qty = 1 where site_id = 37 and product = 'C';
update installations set planned_qty = 24 where site_id = 38 and product = 'A';
update installations set planned_qty = 8 where site_id = 38 and product = 'B';
update installations set planned_qty = 4 where site_id = 38 and product = 'C';
update installations set planned_qty = 4 where site_id = 39 and product = 'A';
update installations set planned_qty = 4 where site_id = 39 and product = 'B';
update installations set planned_qty = 1 where site_id = 39 and product = 'C';
update installations set planned_qty = 9 where site_id = 40 and product = 'A';
update installations set planned_qty = 4 where site_id = 40 and product = 'B';
update installations set planned_qty = 2 where site_id = 40 and product = 'C';
update installations set planned_qty = 6 where site_id = 41 and product = 'A';
update installations set planned_qty = 2 where site_id = 41 and product = 'B';
update installations set planned_qty = 1 where site_id = 41 and product = 'C';
update installations set planned_qty = 10 where site_id = 42 and product = 'A';
update installations set planned_qty = 4 where site_id = 42 and product = 'B';
update installations set planned_qty = 2 where site_id = 42 and product = 'C';
update installations set planned_qty = 4 where site_id = 43 and product = 'A';
update installations set planned_qty = 2 where site_id = 43 and product = 'B';
update installations set planned_qty = 1 where site_id = 43 and product = 'C';
update installations set planned_qty = 29 where site_id = 44 and product = 'A';
update installations set planned_qty = 6 where site_id = 44 and product = 'B';
update installations set planned_qty = 3 where site_id = 44 and product = 'C';
update installations set planned_qty = 3 where site_id = 45 and product = 'A';
update installations set planned_qty = 2 where site_id = 45 and product = 'B';
update installations set planned_qty = 1 where site_id = 45 and product = 'C';
update installations set planned_qty = 11 where site_id = 46 and product = 'A';
update installations set planned_qty = 4 where site_id = 46 and product = 'B';
update installations set planned_qty = 2 where site_id = 46 and product = 'C';
update installations set planned_qty = 4 where site_id = 47 and product = 'A';
update installations set planned_qty = 2 where site_id = 47 and product = 'B';
update installations set planned_qty = 1 where site_id = 47 and product = 'C';
update installations set planned_qty = 2 where site_id = 48 and product = 'A';
update installations set planned_qty = 2 where site_id = 48 and product = 'B';
update installations set planned_qty = 1 where site_id = 48 and product = 'C';
update installations set planned_qty = 8 where site_id = 49 and product = 'A';
update installations set planned_qty = 4 where site_id = 49 and product = 'B';
update installations set planned_qty = 2 where site_id = 49 and product = 'C';
update installations set planned_qty = 57 where site_id = 50 and product = 'A';
update installations set planned_qty = 12 where site_id = 50 and product = 'B';
update installations set planned_qty = 4 where site_id = 50 and product = 'C';
update installations set planned_qty = 86 where site_id = 51 and product = 'A';
update installations set planned_qty = 18 where site_id = 51 and product = 'B';
update installations set planned_qty = 6 where site_id = 51 and product = 'C';
update installations set planned_qty = 3 where site_id = 52 and product = 'A';
update installations set planned_qty = 2 where site_id = 52 and product = 'B';
update installations set planned_qty = 1 where site_id = 52 and product = 'C';
update installations set planned_qty = 2 where site_id = 53 and product = 'A';
update installations set planned_qty = 2 where site_id = 53 and product = 'B';
update installations set planned_qty = 1 where site_id = 53 and product = 'C';
update installations set planned_qty = 171 where site_id = 54 and product = 'A';
update installations set planned_qty = 20 where site_id = 54 and product = 'B';
update installations set planned_qty = 10 where site_id = 54 and product = 'C';
update installations set planned_qty = 4 where site_id = 55 and product = 'A';
update installations set planned_qty = 1 where site_id = 55 and product = 'B';
update installations set planned_qty = 1 where site_id = 55 and product = 'C';
update installations set planned_qty = 51 where site_id = 56 and product = 'A';
update installations set planned_qty = 10 where site_id = 56 and product = 'B';
update installations set planned_qty = 4 where site_id = 56 and product = 'C';
update installations set planned_qty = 114 where site_id = 57 and product = 'A';
update installations set planned_qty = 16 where site_id = 57 and product = 'B';
update installations set planned_qty = 12 where site_id = 57 and product = 'C';
update installations set planned_qty = 77 where site_id = 58 and product = 'A';
update installations set planned_qty = 12 where site_id = 58 and product = 'B';
update installations set planned_qty = 8 where site_id = 58 and product = 'C';
update installations set planned_qty = 12 where site_id = 59 and product = 'A';
update installations set planned_qty = 4 where site_id = 59 and product = 'B';
update installations set planned_qty = 3 where site_id = 59 and product = 'C';

-- 3) 확인용
select s.id, s.name, i.product, i.planned_qty from sites s join installations i on i.site_id = s.id order by s.id, i.product;
